# Generated by Django 5.0.6 on 2024-06-25 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl2complete', models.BooleanField(default=False)),
                ('gradelevel', models.SmallIntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(1)])),
                ('graduationyear', models.IntegerField(null=True)),
                ('bio', models.TextField(null=True)),
                ('town', models.CharField(max_length=120, null=True)),
                ('school', models.CharField(max_length=120, null=True)),
                ('nearestuni', models.CharField(max_length=120, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
