# Generated by Django 5.0.6 on 2024-06-30 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_gradelevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gradelevel',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='graduationyear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2040)]),
        ),
    ]
