# Generated by Django 5.0.6 on 2024-07-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tutor_altavatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
