# Generated by Django 5.0.6 on 2024-07-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_is_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='short_description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='physical_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='virtual_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='additional_comments',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='EssayAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_work_link', models.URLField(null=True)),
                ('student_work_text', models.TextField()),
                ('student_work_file', models.FileField(upload_to='')),
                ('student_comments', models.TextField()),
                ('tutor_feedback', models.TextField()),
                ('tutor_contact', models.TextField()),
                ('is_review_finished', models.BooleanField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_work', models.TextField()),
                ('student_work_file', models.FileField(upload_to='')),
                ('student_work_link', models.URLField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
            ],
        ),
    ]
