# Generated by Django 5.0.6 on 2024-07-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_appointment_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='student_meeting_preference',
            field=models.CharField(choices=[(1, 'In-Person'), (2, 'Virtual')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('IP', 'In-Person'), ('VR', 'Virtual'), ('MST', 'Microsoft Teams'), ('ZM', 'Zoom'), ('DS', 'Discord'), ('EIR', 'Essay In Review')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='is_review_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='student_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='student_work_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='student_work_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='tutor_contact',
            field=models.TextField(default='will be updated shortly'),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='tutor_feedback',
            field=models.TextField(null=True),
        ),
    ]
