# Generated by Django 5.0.6 on 2024-07-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment_student_meeting_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayappointment',
            name='student_work_link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='essayappointment',
            name='student_work_text',
            field=models.TextField(default='', null=True),
        ),
    ]
