# Generated by Django 5.0.6 on 2024-08-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_essayappointment_student_work_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='post_session_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No-Show')], default='scheduled', max_length=20),
        ),
    ]
