# Generated by Django 5.0.6 on 2024-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_appointment_post_session_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
